defaults: &defaults
  sheet:
    timestamp: 0
    name: 1
    kana: 2
    email_pc: 3
    email_phone: 4
    address: 5
    mothers_birthday: 6
    fathers_birthday: 7
    job_style: 8
    job_domain: 9
    number_of_children: 11
    is_male_ok: 29
  job_style:
    # both: 共働き
    # both_single: 共働き(シングルマザー)
    # homemaker: 専業主婦(夫)
    both: 0
    both_single: 1
    homemaker: 2
    str:
      both: '共働き'
      both_single: '共働き ※シングルマザー（ファザー）含む'
      homemaker: 'どちらかが専業主婦（夫）'
  is_male:
    ok: 1
    ng: 0
    str:
      all_participant: '全参加者'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults